### ISSUE TITLE
Download of the TLAPS tar.gz file is missing Zenon, Isabelle and emacs, while TLAPM is downloaded

### ISSUE THREAD

**Issue by fowlerlee** [tlaplus/tlapm#122]
Following the instructions at INRIA's website to install TLAPS is not possible now that the mentioned packages are not downloaded (see heading for missing files). I got Isabelle directly from its site, but am struggling to get zenon installed. Any advice would be great, so that I can go get it myself and avoid using the tar file.

**Steps I have tried:**
1) download with safari or Opera gives the same files.
2) gunzip traps...tar.gz followed by tar xvc tlaps...tar.gz. (Thus I am quite certain the file is not corrupted, just missing what I need)

**Info from INRIA's site where the file is stated as containing zenon, Isabelle and emacs:**
TLAPS tarball: [tlaps-1.4.5.tar.gz](https://github.com/tlaplus/tlapm/archive/v1.4.5.tar.gz)
1. Unpack TLAPS tarball
You can unpack TLAPS by running the following command:
$ tar -xzf tlaps-1.4.5.tar.gz
This creates a directory named tlaps-1.4.5 that contains four subdirectories: tlapm, zenon, isabelle and emacs.

**Comment by fowlerlee** [comment]
in the meantime I just will install from the GitHub provided tar and continue

**Comment by muenchnerkindl** [comment]
Sorry to hear about your problems. The instructions for binary installation should be basically correct, except that they mention a .bin file, and as far as I can tell, the link is wrong because of an outdated file name. The right version should be at https://github.com/tlaplus/tlapm/releases/tag/202210041448.

Installing from source indeed requires installing the back-end provers separately. The Zenon sources are available from https://github.com/tlaplus/tlapm/tree/main/zenon.

@damiendoligez Could you fix the outdated file name for the binary on https://tla.msr-inria.inria.fr/tlaps/content/Download/Binaries/MacOS.html (and similarly for the other OSes)?

@kape1395 @damiendoligez I believe the instructions for installing from source are broken due to the new Dune-based build system?

**Comment by kape1395** [comment]
@muenchnerkindl, indeed, this has changed with the introduction of the Dune-based build. I have updated the build-from-source instructions but forgot about the site instructions. I could update them, but how is the site deployed?

**Comment by muenchnerkindl** [comment]
As you probably saw, the content is here: https://github.com/tlaplus/tlapm/tree/main/doc/web
@damiendoligez: I don't know how this is actually deployed on the Web site, can you please help?
