### ISSUE TITLE
./regression_tests/consensus/consensus_test.tla FAILED

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlapm#14]
See https://github.com/tlaplus/tlapm/runs/1456528879

![Screenshot from 2020-11-26 10-05-45](https://user-images.githubusercontent.com/88777/100381927-f8de0380-2fce-11eb-9039-f70e2a79f07a.png)

**Comment by johnyf** [comment]
This regression has been fixed in commit f8a255f78481e93b05884454ec535478153865ed (test results at: https://github.com/tlaplus/tlapm/runs/1461385376) by bumping to `z3 == 4.8.9`. The test `regression_tests/consensus/consensus_test.tla` passes with `z3 == 4.4.1` (which is how it passed locally on my machine, prior to commit 071faa4663be7cc3dcd67bc684b1b0f6cf632cec, which ensures that the `z3` version installed under the directory `test/lib/tlaps/bin` is run during tests, instead of other `z3` installations that may be in the `$PATH`), fails with `z3 == 4.8.6`, and passes with `z3 == 4.8.9`.

**Comment by johnyf** [comment]
The file https://github.com/tlaplus/tlapm/blob/9e9ae24d1a3b29338d8f86a5cbf4cbc902ee97a3/test/regression_tests/consensus/consensus_test.tla has been moved (https://github.com/tlaplus/tlapm/commit/4480a7013dca5a9a6229b751b1f729283a32c90e#diff-d37a2442818a07ac00093b69e1e581bbfb291f007947fba6f7497c12d6c38307) to https://github.com/tlaplus/tlapm/blob/3f0fad001efa79948fbdca7000118489648791aa/test/fast/regression/consensus/consensus_test.tla, and as of commit 3f0fad001efa79948fbdca7000118489648791aa, the test of this file passes: https://github.com/tlaplus/tlapm/runs/2746752713?check_suite_focus=true#step:10:512.
