### ISSUE TITLE
Bogus error about ENABLED with 1.4.5 TLAPS.tla

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlapm#15]
https://github.com/lemmy/BlockingQueue/ contains a copy of `TLAPS.tla` as released with `1.4.5`.  Re-proving the proofs in, e.g., `BlockingQueue.tla` with what will become TLAPS `1.4.6`, produces a bogus error.

<img width="1071" alt="tlaps-warning" src="https://user-images.githubusercontent.com/88777/100381982-2034d080-2fcf-11eb-8d5a-d6c631565eb2.png">

This probably doesn't need changing in TLAPS, but perhaps a mention in the 1.4.6 release notes.

**Comment by johnyf** [comment]
The reported message arises when running a version of `tlapm` that supports reasoning about `ENABLED`, in a TLA+ module that instantiates a version (or suitable excerpt) of the TLA+ module `TLAPS` from earlier than the initial commit (c9f82aedcb46895a6f6e193a8a35d16aae2f72f1) to this repository (support for `ENABLED` was introduced later than the initial commit).

This earlier change in the module `TLAPS` commented certain theorems that contained `ENABLED` and operator declarations (with the intention of using `BY PTL` instead). When these theorems in the module `TLAPS` are not commented, and support for `ENABLED` is present, then when `tlapm` attempts to instantiate the module `TLAPS`, `tlapm` encounters the theorems that contain `ENABLED` applied to operators that are declared with the keyword `ACTION`. `tlapm` then raises a warning that it cannot instantiate such theorems. (`tlapm` will raise this warning even when no proof directive related to `ENABLED` is used in user modules, because the `INSTANCE` statement will lead `tlapm` to attempt instantiating all the theorems in the module that is being instantiated.)

The warning is raised to inform that certain theorems from the module being instantiated will be absent in the instantiated module, and so proofs that invoke them will not work. This warning is not raised when instantiating versions of the module `TLAPS` in this repository. When this warning is raised due to instantiating modules other than `TLAPS`, then one possibility would be to change the modules to not instantiate theorems that contain `ENABLED` applied to `ACTION` operators (reasoning about instantiations of such theorems is currently unsupported by `tlapm`).

As suggested above (https://github.com/tlaplus/tlapm/issues/15#issue-751765315), in the release notes of TLAPS in the website, in commit 66befe1b6497463ed44c2089d90efedafda8e15e I added a note about this combination of `tlapm` with a version of the TLA+ module `TLAPS.tla` from an older release of TLAPS. Commit 66befe1b6497463ed44c2089d90efedafda8e15e adds a test for the instantiation of the module `TLAPS`, including comments that document this combination of `tlapm` and `TLAPS.tla` versions.

Writing this test revealed a bug unrelated to this issue. That bug has been fixed in commit d7f57d0baf497861943b63fa630bbad09814f7cc.
