### ISSUE TITLE
Proof for ENABLED TRUE fails

### ISSUE THREAD

**Issue by jspenger** [tlaplus/tlapm#157]
Hi, I was using ENABLED within TLAPS and encountered the following curiosity. 

I have not found a way to prove `ENABLED TRUE`. This also applies to similar examples which are *not* of the form `ENABLED <<F>>_v` for which F is a formula and v a variable. See the code example below.

Perhaps this is by design? However, I don't immediately see why `ENABLED TRUE` shouldn't be true, and why TLAPS manages to show that the more complicated form `ENABLED <<TRUE>>_x` holds as shown below.

```TLA
\* Proof Fails
THEOREM ENABLED TRUE
PROOF OBVIOUS

\* Proof Succeeds
THEOREM \A x : ~(x'=x) => ENABLED <<TRUE>>_x
PROOF OBVIOUS

\* Proof Fails
THEOREM \A F : F => ENABLED F
PROOF OBVIOUS

\* Proof Succeeds
THEOREM \A F, v : F /\ ~(v=v') => ENABLED <<F>>_v
PROOF OBVIOUS
```

I understand that in the literature Enabled is usually only used with the form `<<F>>_v`. However the, documentation usually states something along these lines:
> For any action A, we define Enabled A to be the predicate that is true for a state iff it is possible to take an A step starting in that state
> page 6, https://lamport.azurewebsites.net/pubs/lamport-actions.pdf

edit: typo; version: TLA+ Toolbox 1.7.4; tlapm 1.4.5

**Comment by muenchnerkindl** [comment]
The two examples that succeed do so because the formula on the left-hand side of the implication is trivially false. The \A and \E quantifiers range over values, not state variables, so (looking at the second formula) x' just reduces to x because it is considered a constant.

Support for reasoning about ENABLED is relatively recent and is not included in the distribution, which you appear to be using. In order to reason about ENABLED, you will need to build tlapm from source and then use the ExpandENABLED directive. Preliminary examples are in examples/SimpleEventually.tla and examples_draft/SimpleExampleWF.tla.
