### ISSUE TITLE
CHOOSE

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlapm#39]
TLAPS proves both theorems:

```tla
THEOREM ASSUME NEW P(_), NEW S
PROVE \E x: P(x) <=> P(CHOOSE x: P(x))  OBVIOUS 

THEOREM ASSUME NEW P(_), NEW S
PROVE \E x: P(x) <=> P(CHOOSE x: ~P(x))  OBVIOUS   \* Note the negation
```

```shell
markus@avocado:~/$ tlapm --version
1.5.0
markus@avocado:~/$ tlapm O.tla 
(* loading fingerprints in ".tlacache/O.tlaps/fingerprints" *)
(* created new ".tlacache/O.tlaps/O.thy" *)
(* fingerprints written in ".tlacache/O.tlaps/fingerprints" *)
File "./O.tla", line 1, character 1 to line 9, character 4:
[INFO]: All 2 obligations proved.
```

It doesn't prove:

```tla
THEOREM ASSUME NEW P(_), NEW S
PROVE P(CHOOSE x: P(x)) <=> P(CHOOSE x: ~P(x))  OBVIOUS 
```

**Comment by johnyf** [comment]
`tlapm` indeed proves the first two theorems, and not the third sequent. I tried specifying using each backend

After renaming the constant bound by `CHOOSE` (and omitting the declaration `NEW S`), the first theorem could be written:

```tla
THEOREM
    ASSUME NEW P(_)
    PROVE \E x:  P(x) <=> P(CHOOSE u:  P(u))
OBVIOUS
```

I think that this is a theorem, because a value that satisfies the existential quantification is `CHOOSE u:  P(u)` (substituted for `x`).

The second theorem could be written:

```tla
THEOREM
    ASSUME NEW P(_)
    PROVE \E x:  P(x) <=> P(CHOOSE u:  ~ P(u))
OBVIOUS
```

I think that this is a theorem, because a value that satisfies the existential quantification is `CHOOSE u:  ~ P(u)` (substituted for `x`).

The third sequent could be written:

```tla
ASSUME NEW P(_)
PROVE P(CHOOSE x:  P(x)) <=> P(CHOOSE x:  ~ P(x))
```

I think that this sequent is not a theorem, because `tlapm` proves the following theorem:

```tla
---- MODULE Sequent ----
P(x) == x = TRUE


THEOREM
    P(CHOOSE x:  P(x)) # P(CHOOSE x:  ~ P(x))
<1>1. TRUE = CHOOSE x:  P(x)
    BY DEF P
<1>2. P(CHOOSE x:  P(x)) = TRUE
    BY <1>1 DEF P
<1>3. TRUE # CHOOSE x:  ~ P(x)
    BY DEF P
<1>4. TRUE # P(CHOOSE x:  ~ P(x))
    BY <1>3 DEF P
<1> QED
    BY <1>2, <1>4
========================
```

In case that `CHOOSE x:  ~ P(x)` equals `FALSE` (my understanding is that whether this is the case is unspecified by TLA+), then it would also be `~ (P(CHOOSE x:  P(x)) <=> P(CHOOSE x:  ~ P(x)))`.

`tlapm` does also prove that `~ (P(CHOOSE x:  P(x)) <=> P(CHOOSE x:  ~ P(x)))` is a theorem, by replacing the assertion of the theorem above. I did not write this assertion in the theorem because I need to think more about the interpretation of the Boolean operators (i.e., if `CHOOSE x:  ~ P(x)` is a non-Boolean value, e.g., `nonBoolean == CHOOSE r:  r \notin BOOLEAN`, then `P(TRUE) <=> P(nonBoolean)` equals `TRUE <=> (nonBoolean = TRUE)`, which equals `TRUE <=> FALSE`, because `THEOREM nonBoolean \notin BOOLEAN` thus `THEOREM ~ (nonBoolean = TRUE)`).

Sidenote: The identifier `x` is declared by `CHOOSE` within the scope of `\E` that declares `x` in two of the examples given above (SANY raises an error about a Multiply-defined symbol).  `tlapm` gives the same results with this input, and the input after renaming one declaration of `x`. In the first case, `tlapm` may be renaming internally the identifiers to avoid naming conflicts.

**Comment by muenchnerkindl** [comment]
@lemmy : Note that in the formulas that you wrote, the equivalence is in the scope of existential quantification, e.g.

```tla
\E x : (P(x) <=> P(CHOOSE x : ~P(x)))
```

This formula is indeed valid: clearly, the equivalence is true if P(x) holds for all x. If not, P(CHOOSE x : ~P(x)) is false, and the equivalence holds if we pick that value for x.

Perhaps you meant to write

```tla
(\E x : P(x)) <=> P(CHOOSE x : P(x))
```

**Comment by lemmy** [comment]
Sorry for the noise.  @muenchnerkindl is right that I forgot the parentheses.
